opkdmain.o                      : opkda1.o opkda2.o
krome_all.o                     : krome_user_commons.o opkdmain.o
cooling.o                       : krome_all.o
cooling_fine.o                  : cooling.o krome_all.o sinkparticles.o
init_flow_fine.o                : krome_all.o
condinit.o                      : krome_all.o
umuscl.o                        : krome_all.o
interpol_hydro.o                : krome_all.o
init_hydro.o                    : krome_all.o
#radiative_transfer_amr.o       : transfer_ss_amr.o
transfer_ss_amr.o               : richings_dissociation_rates.o
richings_dissociation_rates.o   : leiden_shielding.o
leiden_shielding.o              : krome_all.o
lampray_parameters.o            : krome_all.o
solver_krome.o 			: richings_dissociation_rates.o